# This is a basic workflow to help you get started with Actions

name: Terraform destroy

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Runs a set of commands using the runners shell
      - name: Terraform destroy
        run: |
          terraform init -backend-config="resource_group_name=tf-backend" -backend-config="storage_account_name=felipesatfbackend" -backend-config="container_name=tf-backend" -backend-config="key=iac"
          terraform destroy -auto-approve
